# yaml-language-server: $schema=https://raw.githubusercontent.com/dbt-labs/dbt-jsonschema/main/schemas/latest/dbt_project-latest.json
---
name: tasman_dbt_revenuecat
version: "1.2.3"

config-version: 2
require-dbt-version: [">=1.5.4", "<2.0.0"]

target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]
log-path: "logs"

models:
  tasman_dbt_revenuecat:
    +materialized: table
    +schema: revenuecat
