version: 2

models:
  - name: stg_revenuecat_transactions
    description: 'SCD table to show all revenuecat transactions and each transactions history, excluding sandbox transactions.'
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - store_transaction_id
            - valid_from
    columns:
      - name: billing_issues_detected_at
        data_type: timestamp_ntz
        description: 'A timestamp showing when a billing issue occured. Set to `null` if no billing issues occur.'

      - name: commission_in_purchased_currency
        data_type: float
        description: ''

      - name: commission_in_usd
        data_type: float
        description: ''

      - name: commission_percentage
        data_type: varchar
        description: 'The portion of a transactions price that will be detected by the store for commission.'

      - name: country_code
        data_type: varchar
        description: ''

      - name: country_source
        data_type: varchar
        description: ''

      - name: custom_subscriber_attributes
        data_type: varchar
        description: 'An array which holds custom attributes for the subscriber.'

      - name: effective_end_time
        data_type: timestamp_ntz
        description: 'The expiration timestamp of the subscription which takes into account refunds and grace periods. This provides the most accurate end date.'

      - name: entitlement_identifiers
        data_type: varchar
        description: 'An array of entitlements that the subscription has unlocked for the user. e.g. meal planning.'

      - name: estimated_tax_in_purchased_currency
        data_type: float
        description: ''

      - name: estimated_tax_in_usd
        data_type: float
        description: ''

      - name: expected_end_time
        data_type: timestamp_ntz
        description: 'The timestamp of when the subscription is expected to end. This does not take refunds and grace periods into account.'

      - name: experiment_id
        data_type: varchar
        description: ''

      - name: experiment_variant
        data_type: varchar
        description: ''

      - name: grace_period_end_time
        data_type: timestamp_ntz
        description: 'The expiration time of a grace period. This will be null if the subscriptions does not go into a grace period or the billing issues is solved.'

      - name: is_auto_renewable
        data_type: boolean
        description: 'A boolean flag to show if the subscription is auto renewable or not.'

      - name: is_grace_period
        data_type: boolean
        description: ''

      - name: is_in_intro_offer_period
        data_type: boolean
        description: 'A boolean flag to show if the transaction is in an introductory offer period or not.'

      - name: is_new_revenue
        data_type: boolean
        description: ''

      - name: is_refunded
        data_type: boolean
        description: ''

      - name: is_sandbox
        data_type: boolean
        description: 'A boolean flag to show whether the transaction was made in a sandbox environment. Sandbox transactions are filtered out.'

      - name: is_trial_conversion
        data_type: boolean
        description: 'A boolean flag to show whether the transaction is a conversion from a trial or not.'

      - name: is_trial_period
        data_type: boolean
        description: 'A boolean flag to show whether the transaction is a trial or not.'

      - name: original_store_transaction_id
        data_type: varchar
        description: 'The order ID of the first transaction. This can be used to find all transactions that are part of the same subscription/entitlement period.'

      - name: ownership_type
        data_type: varchar
        description: ''

      - name: platform
        data_type: varchar
        description: 'The last seen platform of the subscriber. e.g. android, iOS.'

      - name: presented_offering
        data_type: varchar
        description: 'The offering presented to users.'

      - name: price_in_purchased_currency
        data_type: varchar
        description: 'The revenue in the purhcased currency. This will be set to 0 if the transaction is refunded.'

      - name: price_in_usd
        data_type: varchar
        description: 'The revenue in USD. This will be set to 0 if the transaction is refunded.'

      - name: proceeds_in_purchased_currency
        data_type: float
        description: 'The revenue caluculated from the price of the subscription, taking tax and store comission into account.'

      - name: proceeds_in_usd
        data_type: float
        description: 'The revenue caluculated from the price of the subscription, taking tax and store comission into account.'

      - name: product_display_name
        data_type: varchar
        description: 'The display name of the product identifier if one has been set.'

      - name: product_duration
        data_type: varchar
        description: 'The standard duration of the product. e.g. P1M(monthly), P1Y(yearly).'

      - name: product_identifier
        data_type: varchar
        description: 'The product identifier that was purchased.'

      - name: purchase_price_in_purchased_currency
        data_type: varchar
        description: 'The amount that the subscription was purchased for. This does not get set to 0 if the transaction is refunded.'

      - name: purchase_price_in_usd
        data_type: varchar
        description: 'The amount that the subscription was purchased for. This does not get set to 0 if the transaction is refunded.'

      - name: purchased_currency
        data_type: varchar
        description: 'The currency that was used for the transaction.'

      - name: rc_last_seen_app_user_id_alias
        data_type: varchar
        description: 'The most recent ID linked to the user purchasing the transaction. This can be used to link to user account.'

      - name: rc_original_app_user_id
        data_type: varchar
        description: 'A unique user identifier to find all of a users transactions.'

      - name: refunded_at
        data_type: timestamp_ntz
        description: 'The time that a transaction was refunded at. This is null if the transaction is not refunded.'

      - name: renewal_number
        data_type: varchar
        description: 'An incrementing number to show how many times the subscription has been renewed. This resets on reactivation.'

      - name: reserved_subscriber_attributes
        data_type: varchar
        description: 'An array to hold extra subscriber attributes.'

      - name: start_time
        data_type: timestamp_ntz
        description: 'The time that the purchase was made.'

      - name: store
        data_type: varchar
        description: 'The source of the transaction. e.g. app_store, play_store.'

      - name: store_transaction_id
        data_type: varchar
        description: 'The unique order ID for the transaction.'
        tests:
          - not_null

      - name: takehome_percentage
        data_type: varchar
        description: ''

      - name: tax_percentage
        data_type: varchar
        description: 'The portion of a transactions price that will be deducted by the store for taxes.'

      - name: unsubscribe_detected_at
        data_type: timestamp_ntz
        description: 'The time that the user opts out of auto renewal.'

      - name: valid_from
        data_type: varchar
        description: 'The time that the record is valid from. Used for SCD.'
        tests:
          - not_null

      - name: valid_to
        data_type: varchar
        description: 'The time that the record is valid to. Used for SCD.'

