name: 'tasman_dbt_revenuecat_integration_tests'
version: '1.0'

config-version: 2

profile: 'tasman_integration_tests'

seed-paths: ["data"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]
log-path: "logs"

vars:
  tasman_dbt_revenuecat:
    revenuecat_table: "SEED_REVENUECAT_TRANSACTIONS_MOCKED"
    revenuecat_filter: "is_sandbox = false"
    revenuecat_custom_subscriber_attributes: ""

seeds:
  tasman_dbt_revenuecat_integration_tests:
    seed_revenuecat_transactions_mocked:
      +column_types:
        rc_original_app_user_id: "string"
        rc_last_seen_app_user_id_alias: "string"
        country: "string"
        product_identifier: "string"
        start_time: "timestamp_ntz"
        end_time: "timestamp_ntz"
        store: "string"
        is_auto_renewable: "boolean"
        is_trial_period: "boolean"
        is_in_intro_offer_period: "boolean"
        is_sandbox: "boolean"
        price_in_usd: "integer"
        takehome_percentage: "float"
        store_transaction_id: "string"
        original_store_transaction_id: "string"
        refunded_at: "timestamp_ntz"
        unsubscribe_detected_at: "timestamp_ntz"
        billing_issues_detected_at: "timestamp_ntz"
        purchased_currency: "string"
        price_in_purchased_currency: "integer"
        entitlement_identifiers: "string"
        renewal_number: "integer"
        is_trial_conversion: "boolean"
        presented_offering: "string"
        reserved_subscriber_attributes: "string"
        custom_subscriber_attributes: "string"
        platform: "string"
        tax_percentage: "integer"
        commission_percentage: "float"
        effective_end_time: "timestamp_ntz"
        grace_period_end_time: "timestamp_ntz"
        ownership_type: "string"
        country_source: "string"
        experiment_id: "integer"
        experiment_variant: "integer"
        purchase_price_in_usd: "integer"
        purchase_price_in_purchased_currency: "integer"
        product_display_name: "string"
        product_duration: "string"
        updated_at: "timestamp_ntz"
        offer: "integer"
        offer_type: "integer"
        first_seen_time: "timestamp_ntz"
        auto_resume_time: "timestamp_ntz"
        _file_name: "string"